spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: replUser
      password: 1234
      jdbc-url: jdbc:mysql://localhost:13306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul

    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: replUser
      password: 1234
      jdbc-url: jdbc:mysql://localhost:13307/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul